# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testmdoal' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testmdoal' do
    # Test name: test mdoal
    # Step # | name | target | value
    # 1 | open | / | 
    @driver.get('http://localhost:3000/')
    # 2 | setWindowSize | 1089x1032 | 
    @driver.manage.resize_to(1089, 1032)
    # 3 | verifyValue | css=.question_title_field | Multiple Choice Question Test
    value = @driver.find_element(:css, '.question_title_field').attribute('value')
    expect(value).to eq('Multiple Choice Question Test')
    # 4 | click | css=.preview_btn | 
    @driver.find_element(:css, '.preview_btn').click
    # 5 | waitForElementPresent | css=.preview_modal | 30000
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.preview_modal') }
    # 6 | click | css=.preview_close_btn | 
    @driver.find_element(:css, '.preview_close_btn').click
    # 7 | waitForElementNotPresent | css=.preview_modal | 30000
    Selenium::WebDriver::Wait.new(timeout: 30).until do
      begin
        !@driver.find_element(:css, '.preview_modal')
      rescue Selenium::WebDriver::Error::NoSuchElementError
        true
      end
    end
  end
end
