# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'test' do
    # Test name: test 
    # Step # | name | target | value
    # 1 | open | / | 
    @driver.get('http://localhost:3000/')
    # 2 | setWindowSize | 1936x1048 | 
    @driver.manage.resize_to(1936, 1048)
    # 3 | click | css=#question_id_2 .delete_btn_icon | 
    @driver.find_element(:css, '#question_id_2 .delete_btn_icon').click
    # 4 | waitForElementVisible | css=.delete_modal | 10000
    Selenium::WebDriver::Wait.new(timeout: 10).until { @driver.find_element(:css, '.delete_modal').displayed? }
    # 5 | waitForElementVisible | css=.delete_modal_delete_btn | 10000
    Selenium::WebDriver::Wait.new(timeout: 10).until { @driver.find_element(:css, '.delete_modal_delete_btn').displayed? }
    # 6 | click | css=.delete_modal_delete_btn | 
    @driver.find_element(:css, '.delete_modal_delete_btn').click
  end
end
