# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testpreview' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testpreview' do
    # Test name: test_preview
    # Step # | name | target | value
    # 1 | open | / | 
    @driver.get('http://localhost:3000/')
    # 2 | setWindowSize | 1206x1039 | 
    @driver.manage.resize_to(1206, 1039)
    # 3 | click | css=.preview_btn | 
    @driver.find_element(:css, '.preview_btn').click
    # 4 | click | css=.next_btn | 
    @driver.find_element(:css, '.next_btn').click
    # 5 | click | css=.next_btn | 
    @driver.find_element(:css, '.next_btn').click
    # 6 | waitForElementVisible | css=.preview_question_title | 30000
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.preview_question_title').displayed? }
    # 7 | click | css=.next_btn | 
    @driver.find_element(:css, '.next_btn').click
    # 8 | waitForElementVisible | css=.preview_question_title | 30000
    Selenium::WebDriver::Wait.new(timeout: 30).until { @driver.find_element(:css, '.preview_question_title').displayed? }
  end
end
